# Generated by Django 4.0.5 on 2022-06-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bar_rate_alter_drink_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='rate',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='-'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='rate',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='-'),
        ),
    ]
