# Generated by Django 4.0.5 on 2022-07-02 12:00

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_bar_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='static/img/', variations={'thumbnail': {'crop': True, 'height': 400, 'width': 300}}),
        ),
        migrations.AddField(
            model_name='pub',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='static/img/', variations={'thumbnail': {'crop': True, 'height': 400, 'width': 300}}),
        ),
    ]
