# Generated by Django 4.0.5 on 2022-07-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_drink_image_pub_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pub',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
